package app.View;

import app.View.Base.LMSForm;

import javax.swing.*;
import java.awt.*;

public class AdminForm implements LMSForm {
    public JPanel Root;
    public JPanel TopTitleLabel;
    public JLabel titleLabel;
    public JButton logOutButton;
    public JTabbedPane AdminSettings;
    public JTabbedPane tabbedPane2;
    public JTabbedPane StudentsSettings;
    public JPanel LogOutPanel;
    public JPanel MainPanel;
    public JPanel BooksSettings;
    public JPanel LibrariansSettings;

    public static void main(String[] args) {
        JFrame frame = new JFrame("AdminForm");
        frame.setContentPane(new AdminForm().Root);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    @Override
    public JButton getLogOutButton() {
        return logOutButton;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Root = new JPanel();
        Root.setLayout(new BorderLayout(0, 0));
        TopTitleLabel = new JPanel();
        TopTitleLabel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        TopTitleLabel.setBackground(new Color(-12620058));
        Font TopTitleLabelFont = this.$$$getFont$$$("Arial", Font.PLAIN, 18, TopTitleLabel.getFont());
        if (TopTitleLabelFont != null) TopTitleLabel.setFont(TopTitleLabelFont);
        Root.add(TopTitleLabel, BorderLayout.NORTH);
        titleLabel = new JLabel();
        Font titleLabelFont = this.$$$getFont$$$("Arial", Font.PLAIN, 22, titleLabel.getFont());
        if (titleLabelFont != null) titleLabel.setFont(titleLabelFont);
        titleLabel.setHorizontalAlignment(0);
        titleLabel.setHorizontalTextPosition(0);
        titleLabel.setText("Admin");
        TopTitleLabel.add(titleLabel);
        MainPanel = new JPanel();
        MainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        Root.add(MainPanel, BorderLayout.CENTER);
        AdminSettings = new JTabbedPane();
        MainPanel.add(AdminSettings, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        BooksSettings = new JPanel();
        BooksSettings.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        AdminSettings.addTab("Books", BooksSettings);
        tabbedPane2 = new JTabbedPane();
        BooksSettings.add(tabbedPane2);
        LibrariansSettings = new JPanel();
        LibrariansSettings.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        AdminSettings.addTab("Librarians", LibrariansSettings);
        StudentsSettings = new JTabbedPane();
        AdminSettings.addTab("Students", StudentsSettings);
        LogOutPanel = new JPanel();
        LogOutPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        Root.add(LogOutPanel, BorderLayout.SOUTH);
        logOutButton = new JButton();
        logOutButton.setText("Log out");
        LogOutPanel.add(logOutButton);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Root;
    }
}


