package app.View;

import javax.swing.*;
import java.awt.*;

public class LogInForm {
    public JPanel Main;
    public JPanel Credentials;
    public JPanel Register;
    public JPanel Title;
    public JTextField loginTextField;
    public JButton logInButton;
    public JButton registerButton;
    public JPasswordField passwordField1;
    public JLabel titleLabel;
    private JTextField textField1;

    public static void main(String[] args) {
        JFrame frame = new JFrame("LogInForm");
        frame.setContentPane(new LogInForm().Main);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public static JFrame createLogInForm() {
        JFrame frame = new JFrame("LogInForm");
        frame.setContentPane(new LogInForm().Main);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        return frame;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Main = new JPanel();
        Main.setLayout(new BorderLayout(0, 0));
        Main.setBackground(new Color(-1));
        Main.setForeground(new Color(-13619152));
        Title = new JPanel();
        Title.setLayout(new BorderLayout(0, 0));
        Title.setMinimumSize(new Dimension(24, 24));
        Title.setOpaque(true);
        Title.setPreferredSize(new Dimension(24, 80));
        Main.add(Title, BorderLayout.NORTH);
        Title.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), null));
        titleLabel = new JLabel();
        Font titleLabelFont = this.$$$getFont$$$("Arial", Font.BOLD, 28, titleLabel.getFont());
        if (titleLabelFont != null) titleLabel.setFont(titleLabelFont);
        titleLabel.setHorizontalAlignment(0);
        titleLabel.setMinimumSize(new Dimension(41, 16));
        titleLabel.setText("Admin");
        Title.add(titleLabel, BorderLayout.CENTER);
        Register = new JPanel();
        Register.setLayout(new BorderLayout(0, 0));
        Register.setOpaque(false);
        Main.add(Register, BorderLayout.SOUTH);
        registerButton = new JButton();
        registerButton.setOpaque(false);
        registerButton.setText("Register");
        Register.add(registerButton, BorderLayout.SOUTH);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setOpaque(false);
        label1.setPreferredSize(new Dimension(103, 26));
        label1.setText("No Account Yet?");
        label1.setVerifyInputWhenFocusTarget(true);
        label1.setVerticalAlignment(1);
        label1.setVerticalTextPosition(0);
        Register.add(label1, BorderLayout.NORTH);
        Credentials = new JPanel();
        Credentials.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 20, 0), -1, -1));
        Credentials.setOpaque(false);
        Main.add(Credentials, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setOpaque(false);
        Credentials.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Arial", Font.BOLD, 20, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setText("Log In");
        panel1.add(label2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 10));
        panel2.setOpaque(false);
        Credentials.add(panel2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        loginTextField = new JTextField();
        loginTextField.setBackground(new Color(-2628377));
        loginTextField.setColumns(0);
        loginTextField.setMargin(new Insets(2, 6, 2, 6));
        loginTextField.setMinimumSize(new Dimension(200, 30));
        loginTextField.setName("");
        loginTextField.setOpaque(true);
        loginTextField.putClientProperty("html.disable", Boolean.FALSE);
        panel2.add(loginTextField, BorderLayout.NORTH);
        passwordField1 = new JPasswordField();
        passwordField1.setBackground(new Color(-2628377));
        passwordField1.setOpaque(true);
        panel2.add(passwordField1, BorderLayout.SOUTH);
        logInButton = new JButton();
        logInButton.setMargin(new Insets(0, 0, 0, 0));
        logInButton.setOpaque(false);
        logInButton.setText("Log In");
        Credentials.add(logInButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Main;
    }

}
