package app.View;

import javax.swing.*;
import java.awt.*;

public class RegistrationForm {
    private JPanel Title;
    private JLabel titleLabel;
    private JPanel Info;
    private JPanel FullName;
    private JLabel fullNameLabel;
    private JTextField fullNameTextField;
    private JPanel Id;
    private JLabel idLabel;
    private JTextField idTextField;
    private JPanel Gender;
    private JLabel genderLabel;
    private JRadioButton maleRadioButton;
    private JRadioButton femaleRadioButton;
    private JPanel Password;
    private JLabel passwordLabel;
    private JPasswordField passwordTextField;
    private JPanel Mail;
    private JLabel mailLabel;
    private JTextField mailTextField;
    private JButton saveButton;
    private JPanel Root;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Root = new JPanel();
        Root.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        Root.setBackground(new Color(-1));
        Title = new JPanel();
        Title.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        Title.setBackground(new Color(-14774810));
        Title.setOpaque(true);
        Title.setPreferredSize(new Dimension(1175, 55));
        Root.add(Title);
        Title.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        Title.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        Title.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        titleLabel = new JLabel();
        Font titleLabelFont = this.$$$getFont$$$(null, -1, 24, titleLabel.getFont());
        if (titleLabelFont != null) titleLabel.setFont(titleLabelFont);
        titleLabel.setForeground(new Color(-1));
        titleLabel.setText("Admin");
        Title.add(titleLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Info = new JPanel();
        Info.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(8, 3, new Insets(0, 0, 0, 0), -1, -1));
        Info.setBackground(new Color(-1));
        Info.setPreferredSize(new Dimension(500, 335));
        Root.add(Info);
        Info.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        FullName = new JPanel();
        FullName.setLayout(new FlowLayout(FlowLayout.LEFT, 2, 1));
        FullName.setBackground(new Color(-1));
        FullName.setPreferredSize(new Dimension(500, 50));
        Info.add(FullName, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        FullName.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        fullNameLabel = new JLabel();
        fullNameLabel.setBackground(new Color(-1));
        fullNameLabel.setForeground(new Color(-12236470));
        fullNameLabel.setOpaque(true);
        fullNameLabel.setText("1. Full Name ");
        FullName.add(fullNameLabel);
        fullNameTextField = new JTextField();
        fullNameTextField.setBackground(new Color(-1));
        fullNameTextField.setPreferredSize(new Dimension(300, 38));
        fullNameTextField.setText("");
        FullName.add(fullNameTextField);
        Id = new JPanel();
        Id.setLayout(new FlowLayout(FlowLayout.LEFT, 4, 5));
        Id.setBackground(new Color(-1));
        Id.setMinimumSize(new Dimension(176, 48));
        Id.setPreferredSize(new Dimension(500, 50));
        Info.add(Id, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        Id.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        idLabel = new JLabel();
        idLabel.setBackground(new Color(-1));
        idLabel.setForeground(new Color(-12236470));
        idLabel.setText("2. ID              ");
        Id.add(idLabel);
        idTextField = new JTextField();
        idTextField.setBackground(new Color(-1));
        idTextField.setPreferredSize(new Dimension(300, 38));
        idTextField.setText("");
        Id.add(idTextField);
        Gender = new JPanel();
        Gender.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        Gender.setBackground(new Color(-1));
        Gender.setPreferredSize(new Dimension(500, 50));
        Info.add(Gender, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        Gender.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        genderLabel = new JLabel();
        genderLabel.setBackground(new Color(-1));
        genderLabel.setForeground(new Color(-12236470));
        genderLabel.setText("3. Gender     ");
        Gender.add(genderLabel);
        maleRadioButton = new JRadioButton();
        maleRadioButton.setBackground(new Color(-1));
        maleRadioButton.setForeground(new Color(-12236470));
        maleRadioButton.setSelected(true);
        maleRadioButton.setText("Male");
        Gender.add(maleRadioButton);
        femaleRadioButton = new JRadioButton();
        femaleRadioButton.setBackground(new Color(-1));
        femaleRadioButton.setForeground(new Color(-12236470));
        femaleRadioButton.setText("Female");
        Gender.add(femaleRadioButton);
        Password = new JPanel();
        Password.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        Password.setBackground(new Color(-1));
        Password.setPreferredSize(new Dimension(500, 50));
        Info.add(Password, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        Password.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        passwordLabel = new JLabel();
        passwordLabel.setBackground(new Color(-1));
        passwordLabel.setForeground(new Color(-12236470));
        passwordLabel.setText("4. Password ");
        Password.add(passwordLabel);
        passwordTextField = new JPasswordField();
        passwordTextField.setBackground(new Color(-1));
        passwordTextField.setForeground(new Color(-12236470));
        passwordTextField.setPreferredSize(new Dimension(300, 38));
        Password.add(passwordTextField);
        Mail = new JPanel();
        Mail.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        Mail.setBackground(new Color(-1));
        Mail.setPreferredSize(new Dimension(500, 50));
        Info.add(Mail, new com.intellij.uiDesigner.core.GridConstraints(5, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        Mail.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        mailLabel = new JLabel();
        mailLabel.setBackground(new Color(-1));
        mailLabel.setForeground(new Color(-12236470));
        mailLabel.setText("5. Mail          ");
        Mail.add(mailLabel);
        mailTextField = new JTextField();
        mailTextField.setBackground(new Color(-1));
        mailTextField.setPreferredSize(new Dimension(300, 38));
        mailTextField.setText("");
        Mail.add(mailTextField);
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        Info.add(spacer3, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
        Info.add(spacer4, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        saveButton = new JButton();
        saveButton.setBackground(new Color(-1));
        saveButton.setForeground(new Color(-10634466));
        saveButton.setMargin(new Insets(0, 0, 0, 0));
        saveButton.setText("Save");
        Info.add(saveButton, new com.intellij.uiDesigner.core.GridConstraints(6, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer5 = new com.intellij.uiDesigner.core.Spacer();
        Info.add(spacer5, new com.intellij.uiDesigner.core.GridConstraints(7, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel1.setBackground(new Color(-1));
        panel1.setPreferredSize(new Dimension(500, 50));
        Info.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-1));
        label1.setForeground(new Color(-12236470));
        label1.setText("    Password ");
        panel1.add(label1);
        final JPasswordField passwordField1 = new JPasswordField();
        passwordField1.setBackground(new Color(-1));
        passwordField1.setForeground(new Color(-12236470));
        passwordField1.setPreferredSize(new Dimension(300, 38));
        panel1.add(passwordField1);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Root;
    }
}
