package app.View;

import app.View.Base.LMSForm;

import javax.swing.*;
import java.awt.*;

public class StudentForm extends LMSForm {
    public JPanel Root;
    public JPanel TopTitlePanel;
    public JLabel titleLabel;
    public JTabbedPane Main;
    public JTabbedPane tabbedPane2;
    public JButton reserveButton;
    public JButton logOutButton;
    public JPanel LogOutPanel;

    public static void main(String[] args) {
        JFrame frame = new JFrame("StudentForm");
        frame.setContentPane(new StudentForm().Root);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Root = new JPanel();
        Root.setLayout(new BorderLayout(0, 0));
        TopTitlePanel = new JPanel();
        TopTitlePanel.setLayout(new BorderLayout(0, 0));
        TopTitlePanel.setBackground(new Color(-12620058));
        Font TopTitlePanelFont = this.$$$getFont$$$("Arial", -1, 18, TopTitlePanel.getFont());
        if (TopTitlePanelFont != null) TopTitlePanel.setFont(TopTitlePanelFont);
        Root.add(TopTitlePanel, BorderLayout.NORTH);
        titleLabel = new JLabel();
        Font titleLabelFont = this.$$$getFont$$$("Arial", Font.PLAIN, 22, titleLabel.getFont());
        if (titleLabelFont != null) titleLabel.setFont(titleLabelFont);
        titleLabel.setForeground(new Color(-1));
        titleLabel.setHorizontalAlignment(0);
        titleLabel.setHorizontalTextPosition(0);
        titleLabel.setText("Student");
        TopTitlePanel.add(titleLabel, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        Root.add(panel1, BorderLayout.CENTER);
        Main = new JTabbedPane();
        Font MainFont = this.$$$getFont$$$("Arial", Font.PLAIN, 18, Main.getFont());
        if (MainFont != null) Main.setFont(MainFont);
        panel1.add(Main, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        Main.addTab("My Books", panel2);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        Main.addTab("Current fine", panel3);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        Font panel4Font = this.$$$getFont$$$("Arial", Font.PLAIN, 18, panel4.getFont());
        if (panel4Font != null) panel4.setFont(panel4Font);
        Main.addTab("All books", panel4);
        tabbedPane2 = new JTabbedPane();
        Font tabbedPane2Font = this.$$$getFont$$$("Arial", Font.PLAIN, 18, tabbedPane2.getFont());
        if (tabbedPane2Font != null) tabbedPane2.setFont(tabbedPane2Font);
        panel4.add(tabbedPane2, BorderLayout.CENTER);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        tabbedPane2.addTab("Publish date", panel5);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        tabbedPane2.addTab("Borrowed", panel6);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        tabbedPane2.addTab("Title", panel7);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        tabbedPane2.addTab("Subject", panel8);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        tabbedPane2.addTab("ISBN", panel9);
        final JPanel panel10 = new JPanel();
        panel10.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        Main.addTab("Settings", panel10);
        LogOutPanel = new JPanel();
        LogOutPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        Root.add(LogOutPanel, BorderLayout.SOUTH);
        reserveButton = new JButton();
        reserveButton.setBackground(new Color(-12633025));
        reserveButton.setText("Reserve");
        LogOutPanel.add(reserveButton);
        logOutButton = new JButton();
        logOutButton.setText("Log Out");
        LogOutPanel.add(logOutButton);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Root;
    }

}
